version: "2"

services:
  #https://hub.docker.com/_/nginx/
  proxy:
    container_name: cjp.local
    image: nginx:1.10-alpine
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on: #to force proxy to start last, add all other services here
      - cjoc
      - cje-test
      - cje-prod
      - shared-agent-ssh
      - shared-agent-jnlp

  #https://hub.docker.com/r/cloudbees/jenkins-operations-center/
  cjoc:
    container_name: cjoc
    image: cloudbees/jenkins-operations-center:1.625.18.5
    environment:
      #TODO set Jenkins URL automatically
      JENKINS_SLAVE_AGENT_PORT: "50000"
      JENKINS_HA: "false"
      JAVA_OPTS: "-Dhudson.TcpSlaveAgentListener.hostName=cjoc -Dhudson.udp=-1 -Dhudson.DNSMultiCast.disabled=true -Djava.awt.headless=true -Xmx1024m -Xms256m"
      #https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties
      JENKINS_OPTS: "--prefix=/cjoc"
    volumes:
      - ./cjoc-data:/var/jenkins_home

  #https://hub.docker.com/r/cloudbees/jenkins-enterprise/
  cje-prod:
    container_name: cje-prod
    image: cloudbees/jenkins-enterprise:1.651.3.1
    environment:
      JENKINS_SLAVE_AGENT_PORT: "50001"
      JENKINS_HA: "false"
      JAVA_OPTS: "-Dhudson.TcpSlaveAgentListener.hostName=cje-prod -Dhudson.udp=-1 -Dhudson.DNSMultiCast.disabled=true -Djava.awt.headless=true -Xmx2048m -Xms256m"
      JENKINS_OPTS: "--prefix=/cje-prod"
    volumes:
      - ./cje-prod-data:/var/jenkins_home

  #https://hub.docker.com/r/cloudbees/jenkins-enterprise/
  cje-test:
    container_name: cje-test
    image: cloudbees/jenkins-enterprise:1.651.3.1
    environment:
      JENKINS_SLAVE_AGENT_PORT: "50002"
      JENKINS_HA: "false"
      JAVA_OPTS: "-Dhudson.TcpSlaveAgentListener.hostName=cje-test -Dhudson.udp=-1 -Dhudson.DNSMultiCast.disabled=true -Djava.awt.headless=true -Xmx2048m -Xms256m"
      JENKINS_OPTS: "--prefix=/cje-test"
    volumes:
      - ./cje-test-data:/var/jenkins_home

  #https://hub.docker.com/r/jenkinsci/ssh-slave/
  shared-agent-ssh:
    container_name: shared-agent-ssh
    image: jenkinsci/ssh-slave
    #command is specific to your env.. see README
    command: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC693QYbxxSveSPC12Q+CvjWrRExV1kNgH3an6v5+tI3n2swoGhXEDelGGlJLQQC6wSm2v6RV6kqCnhg9Pz7Tfm5vHf5MlmbEXr8rkwau1ZowP6/iQwLlLSz/35tGh3MeZo3bTyu5nUMCxFDlG7ZQX6JxeOY3EuqhsGK+qe1BmMN/6oCAsvxZv3ehUzs+SzYkCqrQzdlkh6gT368KqdxWipkpmK6uyIpqon7ptzJB0fMWdexP1GxuicovxE45mr61FdiqgrEemCjQbHTcU/aKv8mbEDm5IR5x/YB7j/z1fZPLr7gOg2VJJN2eNqD/JDcyJv9V02PaxZX+dE7xzOzD5D jenkins@471714444c1d"]

  #https://hub.docker.com/r/cloudbees/jnlp-slave-with-java-build-tools/
  #disregard initial startup error, we can start it later
  #wait for https://github.com/docker/compose/issues/1896
  shared-agent-jnlp:
    container_name: shared-agent-jnlp
    image: cloudbees/jnlp-slave-with-java-build-tools:1.0.0
    environment:
      JENKINS_URL: "http://cjp.local/cjoc"
    #command is specific to your env.. see README
    command: ["31e252ff8e136e8e6b472f56932aea7408af8c190ea4692b0f093b2d88c576fd", "jnlp-shared-cloud"]
